version: '3.8'
services:
  stats-server:
    build: stats-service/stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PORT=9090
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=stats-db
      - DB_USERNAME=admin
      - DB_PASSWORD=password

  stats-db:
    image: postgres:15.1-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - /var/lib/postgresql/data/
      - ./stats-service/stats-server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql

  ewm-service:
    build: main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PORT=8080
      - SERVER_URL=http://stats-server:9090
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=ewm-db
      - DB_USERNAME=admin
      - DB_PASSWORD=password

  ewm-db:
    image: postgres:15.1-alpine
    container_name: ewm-db
    ports:
      - "6551:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - /var/lib/postgresql/data/
      - ./main-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
