CREATE TABLE IF NOT EXISTS hits
(
    id        bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(254)                            NOT NULL,
    uri       VARCHAR(254)                            NOT NULL,
    ip        VARCHAR(15)                             NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT PK_HITS PRIMARY KEY (id)
);